### ISSUE TITLE
when zoomed too far, can't get passed nightly shipment screen

### ISSUE THREAD

**Issue by pondofglue** [thespbgamer/ZoomLevel#13]
if i'm zoomed in too much, the UI at the profits screen before saving will take up the entire screen and I have to restart. I can continue to save by pressing ESC while on the main profits screen. However, the green checkmark after selecting a specific category will be out of frame. Will try to remember to get a pic next time.

**Comment by thespbgamer** [comment]
Yes, please send a picture of the bug, can't recreate it, I have a 1080p screen, max Zoom In value, and max UI size, and I can still click the button (even though it's half cut off).
