### ISSUE TITLE
[Bug]: zoom level make game lag if zoom to far

### ISSUE THREAD

**Issue by bstlyc** [thespbgamer/ZoomLevel#16]
### Describe the bug

i didnt know this is bug or what but everytime i zoom out to my preffered zoom ratio it drops my fps

### To Reproduce

evertime i playyed on my preffered zoom it drops my fps

### Version

latest version

### Settings

![image](https://github.com/thespbgamer/ZoomLevel/assets/81795123/91a867d1-e299-4e13-890c-347102289215)

**Comment by thespbgamer** [comment]
This might be difficult to test, but can you do this please:
• With my mod installed, put the settings that you want (even if it lags).
• Finish the day to save the game.
• Close the game.
• Remove my mod.
• Open the same save without my mod.

If the game still lags without my mod, it's most likely a problem with your PC, if it doesn't, it's my mod.

**Comment by bstlyc** [comment]
ok i already tested it, what i get if i use your mod to zoom out until 35%
and beyond i get constant fps drop but if i playing a normal zoom the fps
is stable with or without ur mod thats the results i get

Pada tanggal Jum, 30 Jun 2023 pukul 16.33 thespbgamer <
***@***.***> menulis:

**Comment by thespbgamer** [comment]
From every test I made, it looks like it's a computer performance issue, not a problem with the mod itself, sorry if this is the answer you were looking for, if you have any extra information feel free to open the issue again.
