### ISSUE TITLE
Downloaded mod, extracted, put into mods...doesnt work

### ISSUE THREAD

**Issue by Wrenaki** [thespbgamer/ZoomLevel#17]
Maybe its not a bug, but I thought this would let me zoom in more? Please let me know if I'm wrong.... if not- it's not zooming anymore on coop split screen than it normally would... I'm blind LOL so I was hoping this mod would help... let me know please.

**Comment by thespbgamer** [comment]
well, i'm  gonna assume that you are using the keybinds listed in the readme file of this github page, if not, you can see that you can increase zoom level with `, (comma)` and decrease it with `. (period)`.<br>
  By holding `Left Shift` or `Right Shift` and using the controls above, you can change the UI Scale.

**Comment by Wrenaki** [comment]
Thank you sooooo much for getting back to me so quickly! I'm pregnant so, yknow, pregnancy brain is effecting everything LOL... I will definitely try this and let you know if it works! (I'm sure it will) also, thank you for understanding what I was trying to say/ask lol

**Comment by thespbgamer** [comment]
It's no problem at all, and if it's not much to ask, please give feedback when you check out the mod again. It's so that I can mark this as an actual issue or close the issue🙂. And I know it might not be my place to say so, but good luck with your pregnancy.

**Comment by Wrenaki** [comment]
Will do! I'm not gonna play multiplayer until later tonight but I'm sure I can check it real quick so I can get back to you!

**Comment by Wrenaki** [comment]
the zoom is HUGE when I'm not on split screen... as for split screen...everything just seems so tiny even on the highest zoom :(

**Comment by thespbgamer** [comment]
> So what you said definitely works, so no bug/issue there..... but I completely misunderstood the zoom features... I thought it was for the map itself.. Do you know of any mods that can safely use a zoom feature to zoom further into the map without breaking the game? The ones I've found all seem to have issues with them. I can see the UI perfectly but my issue is not being able to see the tiny map on my big TV lol

About this, I think only by making the UI bigger, if not you can try "[NPC Map Locations](https://www.nexusmods.com/stardewvalley/mods/239)" because it has a better designed map (and a minimap) and if you don't want the real time location of the NPC's you can always disable it

**Comment by thespbgamer** [comment]
> the zoom is HUGE when I'm not on split screen... as for split screen...everything just seems so tiny even on the highest zoom :(

About this, you can always change the configs with "[Generic Mod Config Menu](https://www.nexusmods.com/stardewvalley/mods/5098)" or by changing the settings in the config file manually, the default max zoom is maybe 200% but you can make it zoom more (but I have not fully tested with zoom levels over 200% because I don't have screens big enough to test those things xD)

**Comment by Wrenaki** [comment]
How funny I JUST downloaded that mod for RSV without even reading this yet. I will definitely try both of those! Thanks so much :)

I have about 50 mods currently, because I wanted to try SVE and RSV together... I've been playing since the beginning and never had modded SV before so I wanted to have a bit of fun with it xD

Changing the "MaxZoomOrUIValue" shouldn't mess with any of the mods right??

**Comment by thespbgamer** [comment]
> How funny I JUST downloaded that mod for RSV without even reading this yet. I will definitely try both of those! Thanks so much :)
> 
> I have about 50 mods currently, because I wanted to try SVE and RSV together... I've been playing since the beginning and never had modded SV before so I wanted to have a bit of fun with it xD
> 
> Changing the "MaxZoomOrUIValue" shouldn't mess with any of the mods right??

Changing the "MaxZoomOrUIValue" **shouldn't** mess with anything, only possible issues are with mods that are not 100% compatible with 1.5, those might have problems because (without getting to technical), many changes were done internally regarding zoom levels. But at max it's only visual bugs from everything I tested so far, hope I'm not wrong xD.

**Comment by Wrenaki** [comment]
For multiplayer split screen, can you zoom in on the UI with the controller? He can zoom with the map now, by clicking the thumb sticks- but he is unable to figure out how to zoom in on the UI. He's having trouble seeing his toolbar.

This is after changing it from 2.0 to 5.0.

**Comment by thespbgamer** [comment]
> For multiplayer split screen, can you zoom in on the UI with the controller? He can zoom with the map now, by clicking the thumb sticks- but he is unable to figure out how to zoom in on the UI. He's having trouble seeing his toolbar.
> 
> This is after changing it from 2.0 to 5.0.

Should be working normaly:
If you use a controller, you can also adjust it by pressing the `left stick` to decrease the zoom and `right stick` to increases the zoom
By holding `Left Trigger & Right Trigger` and using the controls above, you can change the UI Scale.

**Comment by Wrenaki** [comment]
> > For multiplayer split screen, can you zoom in on the UI with the controller? He can zoom with the map now, by clicking the thumb sticks- but he is unable to figure out how to zoom in on the UI. He's having trouble seeing his toolbar.
> > This is after changing it from 2.0 to 5.0.
> 
> Should be working normaly: If you use a controller, you can also adjust it by pressing the `left stick` to decrease the zoom and `right stick` to increases the zoom By holding `Left Trigger & Right Trigger` and using the controls above, you can change the UI Scale.

IT WORKS! Thank you so much for all your help ♥ I really appreciate it! Gameplay on the big screen will be MUCH better now and far less of a headache! I was getting tired of squinting all the time xD Thanks so much again!

**Comment by thespbgamer** [comment]
It's no problem at all, gonna close the issue, but feel free to reopen it if you have any other questions.
