### ISSUE TITLE
Enhancement/Suggestion: Add Support to the android version 

### ISSUE THREAD

**Issue by wsphm** [thespbgamer/ZoomLevel#18]
### Describe the bug

Android phones are not compatible.

### To Reproduce

nothing

### Expected behavior

nothing

### Version

2.3.0

### Settings

nothing

**Comment by thespbgamer** [comment]
@wsphm
Have you tried [this](https://www.youtube.com/watch?v=6fD-5hu-8VU)?

The video shows you how to put a "virtual keyboard" on the screen so you can press the keys from mods that require keypresses. The example is for another mod, but it should work on this one too

**Comment by wsphm** [comment]
> @wsphm你试过吗[这](https://www.youtube.com/watch?v=6fD-5hu-8VU)?
> 
> 这个视频向你展示了如何在屏幕上放置一个虚拟键盘，这样你就可以从需要按键的mods中按下按键。

No, the console display is not compatible, and the mod will not work properly.

**Comment by wsphm** [comment]
![Screenshot_20230924_075926](https://github.com/thespbgamer/ZoomLevel/assets/111187732/1f947fb0-39b0-404a-acbc-78bebaee8855)
Error prompt

**Comment by thespbgamer** [comment]
Well in case of my mod (Zoom Level), it says that you need to update SMAPI, that might be the issue. If that's not possible, please tell me the version of SMAPI that you have so that I can find a fix for that.

**Comment by wsphm** [comment]
Stardew Valley 1.3.6.39,smap 3.18.3.3,Android 13

**Comment by thespbgamer** [comment]
Try this version then, I made a custom version for you to try, feed free to tell me if it works then:

[ZoomLevel 2.3.0 - custom.zip](https://github.com/thespbgamer/ZoomLevel/files/12708126/ZoomLevel.2.3.0.zip)

**Comment by wsphm** [comment]
No error is reported, but zooming with virtual keyboard keys has no effect

**Comment by thespbgamer** [comment]
That's strange, I assume you have the correct keys displayed [here](https://github.com/thespbgamer/ZoomLevel#configjson-file), but if that doesn't work then the android update will have to wait because I can't test it for now.

**Comment by wsphm** [comment]
Only the "KeybindList Movement CameraDown" "button responds

**Comment by thespbgamer** [comment]
that's very strange, if one button works, the other ones should work too, maybe try to rebind the another key

**Comment by wsphm** [comment]
Tested again.Only the move view function is available

**Comment by thespbgamer** [comment]
Might be a limitation of the mobile version, when I can, i'll check that

**Comment by thespbgamer** [comment]
Sorry it took so long, forgot to answer to be honest, but according to [this](https://stardewcommunitywiki.com/Modding:Installing_SMAPI_on_Android), support for 1.5 is still not official and not working at the moment.

> Stardew Valley 1.5 and SMAPI 3.8 aren't available on Android yet. You may need to use older versions of many mods.
