### ISSUE TITLE
[Bug]: The zoom level in the settings tab does not match with the real zoom level 

### ISSUE THREAD

**Issue by igoticecream** [thespbgamer/ZoomLevel#19]
### Describe the bug

There is a desynchronization between the real zoom level and the one shown by the settings tab when I use this mod

### To Reproduce

1. Load the game
2. Use the hotkey to scroll all the way up to 200%
3. Open the settings tab and check the zoom level, should be 200%
4. Use the hotkey to decrease the zoom level once and check again the zoom level, should have decreased by ZoomOrUILevelDecreaseValue
5. Doing this until 125% the settings tab shows the correct zoom level. Decreasing once more makes the zoom level to go from 125% to 75%, when the real zoom level is 120%.
6. If you cant reproduce it, use my config.json

See screenshots between zoom level 125% and 120% (game reports 75%)

### Expected behavior

Zoom level in the settings tab should be 120% and not 75%

### Version

I'm on the latest version

### Settings

```json
{
  "KeybindListHoldToChangeUI": "LeftControl",
  "KeybindListIncreaseZoomOrUI": "MouseX2",
  "KeybindListDecreaseZoomOrUI": "MouseX1",
  "KeybindListResetZoomOrUI": "None",
  "KeybindListMaxZoomOrUI": "None",
  "KeybindListMinZoomOrUI": "None",
  "KeybindListZoomToCurrentMapSize": "None",
  "KeybindListPresetZoomAndUIValues": "None",
  "KeybindListMovementCameraUp": "None",
  "KeybindListMovementCameraDown": "None",
  "KeybindListMovementCameraLeft": "None",
  "KeybindListMovementCameraRight": "None",
  "KeybindListMovementCameraReset": "None",
  "KeybindListToggleUIVisibility": "None",
  "KeybindListToggleHideUIWithCertainZoom": "None",
  "KeybindListToggleAnyKeyToResetCamera": "None",
  "KeybindListToggleAutoZoomToCurrentMapSize": "None",
  "KeybindListTogglePresetOnLoadSaveFile": "None",
  "ZoomOrUILevelIncreaseValue": 0.05,
  "ZoomOrUILevelDecreaseValue": -0.05,
  "ResetZoomOrUIValue": 1.0,
  "MaxZoomOrUIValue": 2.0,
  "MinZoomOrUIValue": 0.35,
  "ZoomLevelThatHidesUI": 0.35,
  "CameraMovementSpeedValue": 15,
  "PresetZoomLevelValue": 1.2,
  "PresetUIScaleValue": 1.2,
  "SuppressControllerButtons": true,
  "AutoZoomToCurrentMapSize": false,
  "AnyButtonToCenterCamera": true,
  "HideUIWithCertainZoom": false,
  "PresetOnLoadSaveFile": true,
  "ZoomAndUIControlEverywhere": false
}
```

### Extra Attachments

![125%](https://github.com/thespbgamer/ZoomLevel/assets/3914859/4c07c4e4-8285-4c75-8fc4-d6ffab325852)
![120%](https://github.com/thespbgamer/ZoomLevel/assets/3914859/696f6359-22a0-41eb-926b-533a94540955)

**Comment by thespbgamer** [comment]
I think this is a limitation, but I'm gonna double check this in the next few days.

**Comment by thespbgamer** [comment]
Confirmed, it's a game limitation, From what I checked, I can't change the values there (are static and lowest value is 75%) so I can't do anything about that, sorry. Gonna close this, if you have any other bug or suggestion feel free to ask.
