### ISSUE TITLE
Latest version breaks UI-related mods by misaligning them without even zooming in (Host and Farm Hand)

### ISSUE THREAD

**Issue by jaydee0004** [thespbgamer/ZoomLevel#3]
The latest version breaks HP Bars and everything related  to UI Info Suite.

Somehow the save file also gets permanently broken by the latest version (Misaligned UI elements all over).

Reverting to a backup save file and removing the latest version of ZoomLevel fixed the issue.

**Comment by thespbgamer** [comment]
That's a UI Info Suite issue, most likely because it's not an official version, it tends to break stuff, and those issues have been reported in the UI Info Suite Github issues.

**Comment by jaydee0004** [comment]
Is there a way to remove ZoomLevel's data on the save file? At least let me know what I can do to temporarily fix my save file.

**Comment by thespbgamer** [comment]
> Is there a way to remove ZoomLevel's data on the save file? At least let me know what I can do to temporarily fix my save file.
> 
> EDIT: Also wanting to fix my Farm hand's side of the save file.

You should be able to download an older version of the mod on nexus and on github, if that does not work, i might not be able to help you
