### ISSUE TITLE
Zooming in on character

### ISSUE THREAD

**Issue by lucadris** [thespbgamer/ZoomLevel#5]
First of all, thank you so much for creating this wonderful mod. I was wondering if a "zooming in on the player character" function might be potentially added to the mod in the future?

I used to use Yesst's Zoom Level Keybinding in SDV 1.4, and when I was trying to choose a place to construct a building, if I pressed a hotkey to either zoom in or zoom out, the screen automatically focused on where my Farmer character currently was, making it easier to place the building on the spot where I wanted. That function seems to be unavailable in ZoomLevel and I thought it'd be even more convenient if there was like a 'spotlight' function, to move the screen to where the Farmer was.

Again, thank you for your wonderful mod and have a lovely day! : )

**Comment by thespbgamer** [comment]
Please check new release if this is what you wanted.
