### ISSUE TITLE
[Feature Request] More Hotkeys

### ISSUE THREAD

**Issue by Zamiell** [thespbgamer/ZoomLevel#8]
Greetings,

Thanks so much for making/updating this mod! It is so fantastic and saves so much time.

For me, the main use-case for this mod is to examine the layout of a new floor of the mines that I just reached. In vanilla, you can take a screenshot and then look at the screenshot in order to get a picture of the full layout. With this mod, you can instead spam the zoom out keys, study the floor for a bit, and then hit the zoom reset hotkey. But this is still quite cumbersome, so some small improvements would be greatly appreciated:

## 1) Max-Zoom Hotkey

When I want to see the full map layout, I don't want to have to spam the zoom out button over and over. It would be really nice if there were simply a max-zoom hotkey, that goes all the way to the maximum defined zoom value in the config.json.

(You might as well also add a min-zoom hotkey too!)

## 2) UI Visibility Toggle Hotkey

When zooming out, the pause UI gets in the way of what you want to see. It would be great if you could make a hotkey that toggles between a UI 0% zoom (which should completely hide it) or a 1% zoom (if 0% is not possible) and the previously remembered value.

## 3) Setting for Automatic UI Hiding when Zoom is over N Percent

At really zoomed-out levels, it can be safely assumed that the player isn't going to permanently play like that - they are only zooming out so that they can see the full floor layout. Naturally, when doing this, the game is going to be paused, so that in-game time is not passing. And subsequently, the pause UI is going to block some parts of the floor layout.

So, if the zoom level is above some arbitrary threshold, then the UI should automatically be hidden (and automatically returned when the zoom level is set to a more normal value).

## 4) Improved Max-Zoom Hotkey

Once #1 above is implemented, it could also be improved. It is very hard to see individual tiles when the game is zoomed-out really far like that. So, the mod can help with this by calculating what the smallest possible zoom level would be while still having every tile be visible, and then zooming to that exact level. Maybe this could be a separate hotkey than the normal "Max-Zoom" hotkey - you could call it "Max-Zoom Smart", or something like that, and allow binding it on a separate key.

## 5) Camera Scrolling / Panning / Movement

While potentially outside the scope of this mod, I figure I will bring this up as well. As I said earlier, I consider Zoom Level to be a replacement for the screenshot feature. When viewing a screenshot of a mines floor, you can start at a high-level overview of the floor, and then zoom in on a particular far-away spot  to see more-clearly what kind of monsters/gems are there.

You can sort-of do this with Zoom Level, but not really. On really big floors, you can zoom out to see the whole floor, but at that point you then have to squint to see what exactly is on the part that is far away from you. And sometimes, even that is not good enough - you have to resort back to taking a screenshot of the area, just like if you were playing vanilla.

Is there some way for the mod to allow you to move the camera in some way, so then when you hit the zoom-in hotkey, it won't be locked in to the player anymore? I envision something like a "Detach Camera" modifier key that you hold down, and while it is held down, you can move the mouse cursor to the edge of the screen to scroll it. And then, when you are finished exploring, you can release the modifier key to snap the camera back on to the player again.

**Comment by thespbgamer** [comment]
Right now I don't have much time for that, but they are great ideas to be added.
Still need to check if it's possible to implement, but I'll check on that at a later date.

**Comment by thespbgamer** [comment]
Very beta version of the first one is added, still low on time, but might add more soon

**Comment by Zamiell** [comment]
Thank you!

**Comment by thespbgamer** [comment]
Added the second feature @Zamiell

**Comment by Zamiell** [comment]
Thank you!

**Comment by thespbgamer** [comment]
Third feature added

**Comment by Zamiell** [comment]
Woot, thank you!

**Comment by thespbgamer** [comment]
Fourth feature added

**Comment by thespbgamer** [comment]
Fifth feature added, will be released in the next update (should be early next month)

**Comment by Zamiell** [comment]
Awesome, thank you!
